name: ZMusicBox
version: 3.1.0
api: [2.0.0]
author: Zzm
description: Play music in your server
main: ZMusicBox\ZMusicBox

commands:
 music:
  permission: ZMusicBox.music
  description: Manage the music in your server
  usage: /music <start|stop|next|loop>

permissions:
 ZMusicBox:
  default: true
  description: Allows use of ZMusicBox plugin functionality
  children:
    ZMusicBox.music:
      default: op
      description: ZMusicBox Commands
      children:
        ZMusicBox.music.start:
          description: Start playing a random song
        ZMusicBox.music.stop:
          description: Stop playing the current song
        ZMusicBox.music.next:
          description: Start playing a random song
        ZMusicBox.music.loop:
          description: Switch single loop
          children:
            ZMusicBox.music.loop.on:
              description: Turn on single song loop
            ZMusicBox.music.loop.off:
              description: Turn off single song loop
    ZMusicBox.canhear:
      description: Can hear the song playing
    ZMusicBox.popup:
      description: Display the name of the song currently playing
      children:
        ZMusicBox.popup.progress:
          description: Display the song playing progress bar
